#!/usr/bin/env python3
"""Export SLRR TUFA class method indexes for the C++ host JVM.

Usage:
  python native/tools/export_class_index.py
"""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "tufaLASR"))
from tufa_slrr import parse_tufa_auto  # noqa: E402

GAME = ROOT / "Street Legal Racing - Redline"
OUT = ROOT / "native" / "engine" / "data" / "class_index.txt"

# Seed set for phase-1 JVM smoke (expand later).
GLOBS = [
    "system/Scripts/lang/*.class",
    "system/Scripts/io/*.class",
    "system/Scripts/util/resource/*.class",
]


def main() -> int:
    lines: list[str] = ["# class_index — generated by export_class_index.py", ""]
    n_classes = 0
    n_methods = 0
    for pattern in GLOBS:
        for path in sorted((GAME).glob(pattern)):
            data = path.read_bytes()
            if data[:4] != b"TUFA":
                continue
            try:
                cf = parse_tufa_auto(data)
            except Exception as e:
                lines.append(f"# FAIL {path.relative_to(GAME)}: {e}")
                continue
            rel = path.relative_to(GAME).as_posix()
            lines.append(f"CLASS {cf.this_name}")
            lines.append(f"FILE {rel}")
            if cf.super_name:
                lines.append(f"SUPER {cf.super_name}")
            for m in cf.methods:
                native = 1 if (m.tree_index < 0 or (
                    m.tree_index < len(cf.trees) and len(cf.trees[m.tree_index]) == 0
                )) else 0
                # Also treat flag bit if ever set
                if m.flags & 0x100:
                    native = 1
                lines.append(f"METHOD {m.name} {m.signature} native={native}")
                n_methods += 1
            lines.append("")
            n_classes += 1

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {OUT} ({n_classes} classes, {n_methods} methods)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
