#!/usr/bin/env python3
"""Generate host no-op C++ bodies for selected FQNs from natives_table.inc."""
from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
INC = ROOT / "native" / "engine" / "include" / "natives_table.inc"
# Legacy monolith path — Runtime/ now owns split domain files. Pass --force to emit.
OUT = ROOT / "native" / "engine" / "Runtime" / "_legacy_generated_world.cpp"

FQNS = {
    "java.util.resource.GroundRef",
    "java.util.resource.Animation",
    "java.util.resource.ParticleSystem",
    "java.sound.Sound",
    "java.render.GfxEngine",
    "java.render.Viewport",
    "java.render.Camera",
    "java.render.Text",
    # Controller.user_* live in Runtime/IO/IO.cpp (mapAxis table)
    "java.io.MouseCursor",
    "java.lang.GameType",
    # game layer — host no-ops until reverse deepens
    "java.game.parts.WheelRef",
    "java.game.parts.Part",
    "java.game.parts.bodypart.Chassis",
    "java.game.parts.DynoData",
    "java.game.parts.SfxTable",
    "java.game.Painter",
    # Vehicle.getSpeedSquare/getHorn/hasCrime live in Runtime/Resources/GameRef.cpp
    "java.game.GameLogic",
    "java.game.Navigator",
}

DECL_RE = re.compile(
    r"^(?P<ret>[\w:<>\*]+)\s+(?P<name>java_[\w]+)\((?P<args>[^)]*)\);"
)


def main() -> int:
    if "--force" not in sys.argv:
        print(
            "gen_world_stubs: domain natives live under engine/Runtime/** "
            "(Parts, Render, …).\n"
            "Refusing to emit a monolith. Pass --force to write",
            OUT,
        )
        return 0
    prefixes = [fqn.replace(".", "_") + "_" for fqn in FQNS]
    bodies: list[str] = [
        "// AUTO-GENERATED by native/tools/gen_world_stubs.py — do not edit",
        '#include "natives.hpp"',
        '#include "host_objects.hpp"',
        '#include "runtime.hpp"',
        "",
        "namespace inv {",
        "",
    ]
    count = 0
    for line in INC.read_text(encoding="utf-8").splitlines():
        m = DECL_RE.match(line.strip())
        if not m:
            continue
        name = m.group("name")
        if not any(name.startswith(p) for p in prefixes):
            continue
        # Hand-implemented in Runtime/Resources/GameRef.cpp / Runtime/System/GameType.cpp.
        if name in {
            "java_util_resource_GroundRef_addTrafficCar",
            "java_util_resource_GroundRef_remTrafficCar",
            "java_util_resource_GroundRef_notifyTrafficCar",
            "java_util_resource_GroundRef_addTrafficN",
            "java_util_resource_GroundRef_addTrafficP",
            "java_util_resource_GroundRef_delTraffic",
            "java_util_resource_GroundRef_setPedestrianDensityN",
            "java_util_resource_GroundRef_addPedestrianType",
            "java_util_resource_GroundRef_remPedestrianType",
            "java_game_Navigator_updateNavigator",
            "java_lang_GameType_remNotification",
            "java_lang_GameType_addNotification",
            "java_lang_GameType_addNotification_1",
            "java_lang_GameType_addTimer",
            "java_lang_GameType_removeAllTimers",
            "java_lang_GameType_setEventMask",
            "java_lang_GameType_clearEventMask",
            "java_lang_GameType_registerCallback",
            "java_lang_GameType_unregisterCallback",
            "java_lang_GameType_unregisterCallbacks",
            "java_lang_GameType_createNativeInstance",
        }:
            continue
        ret = m.group("ret")
        args = m.group("args")
        bodies.append(f"{ret} {name}({args}) {{")
        for a in args.split(","):
            a = a.strip()
            if not a:
                continue
            ident = a.split()[-1].lstrip("*&")
            if ident:
                bodies.append(f"  (void){ident};")
        if ret == "void":
            pass
        elif ret.endswith("*"):
            if any(k in name for k in ("getOri", "Direction", "Ypr")):
                bodies.append("  return ypr_new(0, 0, 0);")
            elif any(
                k in name
                for k in ("getPos", "alignToRoad", "getNearestCross", "getPickedPos")
            ):
                bodies.append("  return vec3_new(0, 0, 0);")
            else:
                bodies.append("  return nullptr;")
        elif ret in ("float", "double"):
            bodies.append("  return 0;")
        elif ret == "bool":
            bodies.append("  return false;")
        else:
            bodies.append("  return 0;")
        bodies.append("}")
        bodies.append("")
        count += 1

    bodies.append("}  // namespace inv")
    bodies.append("")
    OUT.write_text("\n".join(bodies), encoding="utf-8")
    print(f"Wrote {OUT} ({count} functions)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
