#!/usr/bin/env python3
"""Generate C++ native stub declarations from natives_inventory.json.

Usage:
  python native/tools/gen_native_stubs.py
"""
from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
INV = ROOT / "native" / "docs" / "natives_inventory.json"
OUT_H = ROOT / "native" / "engine" / "include" / "natives_table.inc"
OUT_CPP = ROOT / "native" / "engine" / "Core" / "natives_stubs.cpp"

JAVA_TO_CXX = {
    "void": "void",
    "int": "int32_t",
    "float": "float",
    "boolean": "bool",
    "byte": "int8_t",
    "short": "int16_t",
    "long": "int64_t",
    "double": "double",
    "char": "uint16_t",
}


def sanitize_ident(s: str) -> str:
    s = s.replace(".", "_").replace("/", "_").replace("$", "_")
    s = re.sub(r"[^0-9A-Za-z_]", "_", s)
    if s and s[0].isdigit():
        s = "_" + s
    return s


def map_type(java_type: str) -> str:
    t = java_type.strip()
    # strip generics / arrays lightly
    t = t.replace("[]", "*")
    if t in JAVA_TO_CXX:
        return JAVA_TO_CXX[t]
    # object / unknown → opaque handle pointer
    return "InvObject*"


def parse_args(args: str) -> list[tuple[str, str]]:
    args = args.strip()
    if not args:
        return []
    out: list[tuple[str, str]] = []
    depth = 0
    cur = []
    for ch in args:
        if ch == "<":
            depth += 1
            cur.append(ch)
        elif ch == ">":
            depth = max(0, depth - 1)
            cur.append(ch)
        elif ch == "," and depth == 0:
            part = "".join(cur).strip()
            if part:
                out.append(split_arg(part))
            cur = []
        else:
            cur.append(ch)
    part = "".join(cur).strip()
    if part:
        out.append(split_arg(part))
    return out


def split_arg(part: str) -> tuple[str, str]:
    part = re.sub(r"\s+", " ", part).strip()
    # type name  OR  type
    m = re.match(r"^(.+?)\s+(\w+)$", part)
    if m:
        return m.group(1).strip(), m.group(2)
    return part, f"a{len(part)}"


def cxx_sig(method: dict, with_name: bool = True) -> str:
    ret = map_type(method["return"])
    args = parse_args(method.get("args", ""))
    is_static = "static" in method.get("modifiers", "").split()
    params: list[str] = []
    if not is_static:
        params.append("InvObject* self")
    for i, (jt, name) in enumerate(args):
        params.append(f"{map_type(jt)} {sanitize_ident(name) or f'a{i}'}")
    fn = sanitize_ident(f"{method['fqn']}_{method['name']}")
    if with_name:
        return f"{ret} {fn}({', '.join(params)})"
    return f"{ret} ({', '.join(params)})"


def main() -> int:
    data = json.loads(INV.read_text(encoding="utf-8"))
    natives = data["natives"]

    # header include fragment: declare + table entries
    decls: list[str] = []
    table: list[str] = []
    stubs: list[str] = []

    decls.append("// AUTO-GENERATED by native/tools/gen_native_stubs.py — do not edit")
    decls.append("// Included inside namespace inv from natives.hpp")
    decls.append("")

    # Overload-safe names: FQN_method[_N]
    # Bodies provided under engine/Runtime/** — still emit decls + table.
    HAND_WRITTEN = {
        ("java.lang.System", "exit"),
        ("java.lang.System", "log"),
        ("java.lang.System", "buildNumber"),
        ("java.lang.System", "gc"),
        ("java.lang.System", "runFinalization"),
        ("java.lang.System", "compileAll"),
        ("java.lang.System", "analyze"),
        ("java.lang.System", "arraycopy"),
        ("java.lang.System", "currentTime"),
        ("java.lang.System", "simTime"),
        ("java.lang.System", "timeWarp"),
        ("java.lang.System", "syncGameTime"),
        ("java.lang.System", "setMeasure"),
        ("java.lang.System", "getConfigOptions"),
        ("java.lang.System", "netHost"),
        ("java.lang.System", "netJoin"),
        ("java.lang.System", "netLeave"),
        ("java.lang.System", "openLib"),
        ("java.lang.System", "isLoadingReset"),
        ("java.lang.System", "isLoading"),
        ("java.lang.System", "setLdPriority"),
        ("java.lang.String", "finalize"),
        ("java.lang.String", "token"),
        ("java.lang.String", "intValue"),
        ("java.lang.String", "floatValue"),
        ("java.lang.String", "append"),
        ("java.lang.String", "length"),
        ("java.lang.Integer", "toString"),
        ("java.lang.Integer", "toHexString"),
        ("java.lang.Float", "toString"),
        ("java.lang.Math", "random"),
        ("java.lang.Math", "sqrt"),
        ("java.lang.Math", "randomize"),
        ("java.lang.Math", "setrandseed"),
        ("java.lang.Object", "wait"),
        ("java.lang.Object", "notify"),
        ("java.lang.Object", "notifyAll"),
        ("java.lang.Object", "toString"),
        ("java.lang.Object", "enableGC"),
        ("java.lang.Object", "disableGC"),
        ("java.lang.Thread", "getPriority"),
        ("java.lang.Thread", "setPriority"),
        ("java.lang.Thread", "setDaemon"),
        ("java.lang.Thread", "init"),
        ("java.lang.Thread", "start"),
        ("java.lang.Thread", "stop"),
        ("java.lang.Thread", "isAlive"),
        ("java.lang.Thread", "sleep"),
        ("java.lang.Thread", "suspend"),
        ("java.lang.Thread", "resume"),
        ("java.io.File", "open"),
        ("java.io.File", "close"),
        ("java.io.File", "write"),
        ("java.io.File", "readInt"),
        ("java.io.File", "readFloat"),
        ("java.io.File", "readResID"),
        ("java.io.File", "readString"),
        ("java.io.File", "delete"),
        ("java.io.File", "copy"),
        ("java.io.File", "move"),
        ("java.io.File", "exists"),
        ("java.io.FindFile", "first"),
        ("java.io.FindFile", "next"),
        ("java.io.FindFile", "close"),
        ("java.io.Input", "getAxis"),
        ("java.io.Input", "getDeviceName"),
        ("java.io.Input", "mapAxis"),
        ("java.io.Input", "setAxisSmooth"),
        ("java.io.Input", "activeAxis"),
        ("java.io.Input", "axisName"),
        ("java.io.Input", "lastKey"),
        ("java.io.Input", "createHotkey"),
        ("java.io.Input", "deleteHotkey"),
        ("java.io.Input", "checkHotkeys"),
        ("java.io.Input", "flushHotkeys"),
        ("java.lang.Vector3", "length"),
        ("java.lang.Vector3", "distance"),
        ("java.lang.Vector3", "normalize"),
        ("java.lang.Vector3", "rotate"),
        ("java.lang.Ypr", "mul"),
        ("java.util.resource.GameRef", "create"),
        ("java.util.resource.GameRef", "create_native"),
        ("java.util.resource.GameRef", "getFlags"),
        ("java.util.resource.GameRef", "setFlags"),
        ("java.util.resource.GameRef", "clearFlags"),
        ("java.util.resource.GameRef", "getOri"),
        ("java.util.resource.GameRef", "getPos"),
        ("java.util.resource.GameRef", "getVel"),
        ("java.util.resource.GameRef", "setPos"),
        ("java.util.resource.GameRef", "setMatrix"),
        ("java.util.resource.GameRef", "setParent"),
        ("java.util.resource.GameRef", "setState"),
        ("java.util.resource.GameRef", "isEmpty"),
        ("java.util.resource.GameRef", "isScripted"),
        ("java.util.resource.GameRef", "getScriptInstance"),
        ("java.util.resource.GameRef", "getInfo"),
        ("java.util.resource.GameRef", "queueEvent"),
        ("java.util.resource.GameRef", "setActiveCollision"),
    }

    HAND_RESOURCE_FQN = {
        "java.util.resource.GameRef",
        "java.util.resource.ResourceRef",
        "java.util.resource.RenderRef",
        "java.util.resource.PhysicsRef",
        "java.util.resource.SfxRef",
        "java.util.resource.GroundRef",
        "java.util.resource.Animation",
        "java.util.resource.ParticleSystem",
        "java.sound.Sound",
        "java.render.GfxEngine",
        "java.render.Viewport",
        "java.render.Camera",
        "java.render.Text",
        "java.io.Controller",
        "java.io.MouseCursor",
        "java.lang.GameType",
        "java.game.parts.WheelRef",
        "java.game.parts.Part",
        "java.game.parts.bodypart.Chassis",
        "java.game.parts.DynoData",
        "java.game.parts.SfxTable",
        "java.game.Painter",
        "java.game.Vehicle",
        "java.game.GameLogic",
        "java.game.Navigator",
    }

    seen: dict[str, int] = {}
    hand_count = 0
    for m in natives:
        base = sanitize_ident(f"{m['fqn']}_{m['name']}")
        n = seen.get(base, 0)
        seen[base] = n + 1
        fn = base if n == 0 else f"{base}_{n}"
        m["_cxx_name"] = fn
        ret = map_type(m["return"])
        args = parse_args(m.get("args", ""))
        is_static = "static" in m.get("modifiers", "").split()
        params: list[str] = []
        if not is_static:
            params.append("InvObject* self")
        for i, (jt, name) in enumerate(args):
            params.append(f"{map_type(jt)} {sanitize_ident(name) or f'a{i}'}")
        sig = f"{ret} {fn}({', '.join(params)})"
        decls.append(f"{sig};")
        table.append(
            "  {"
            f'"{m["fqn"]}", "{m["name"]}", "{m["signature"]}", '
            f"{'true' if is_static else 'false'}, "
            f"reinterpret_cast<void*>(&{fn})"
            "},"
        )
        if (m["fqn"], m["name"]) in HAND_WRITTEN or m["fqn"] in HAND_RESOURCE_FQN:
            hand_count += 1
            continue
        stubs.append(f"{sig} {{")
        stubs.append(f'  inv_log_native("{m["fqn"]}", "{m["name"]}");')
        if ret == "void":
            stubs.append("}")
        elif ret == "bool":
            stubs.append("  return false;")
            stubs.append("}")
        elif ret.endswith("*"):
            stubs.append("  return nullptr;")
            stubs.append("}")
        elif ret in ("float", "double"):
            stubs.append("  return 0;")
            stubs.append("}")
        else:
            stubs.append("  return 0;")
            stubs.append("}")
        stubs.append("")

    OUT_H.parent.mkdir(parents=True, exist_ok=True)
    OUT_H.write_text("\n".join(decls) + "\n", encoding="utf-8")

    cpp_lines = [
        "// AUTO-GENERATED by native/tools/gen_native_stubs.py — do not edit",
        '// Hand-written bodies: see engine/Runtime/** (System, Parts, …)',
        '#include "natives.hpp"',
        "",
        "namespace inv {",
        "",
        *stubs,
        "const NativeEntry kNativeTable[] = {",
        *table,
        "};",
        "",
        "const size_t kNativeTableCount = sizeof(kNativeTable) / sizeof(kNativeTable[0]);",
        "",
        "}  // namespace inv",
        "",
    ]
    OUT_CPP.parent.mkdir(parents=True, exist_ok=True)
    OUT_CPP.write_text("\n".join(cpp_lines) + "\n", encoding="utf-8")
    print(f"Wrote {OUT_H}")
    print(f"Wrote {OUT_CPP} ({len(natives) - hand_count} stubs, {hand_count} hand-written)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
